export const CREATE = 'CREATE'
export const FETCH_ALL = 'FETCH_ALL'
export const FETCH_POST = 'FETCH_POST'
export const SET_CURRENT_ID = 'SET_CURRENT_ID'
export const UPDATE = 'UPDATE'
export const DELETE = 'DELETE'
export const GET_LIVING_LOCATION_POSTS = 'GET_LIVING_LOCATION_POSTS'